# ===================================================================
# CONFIGURATION GENERALE DE L'APPLICATION
# ===================================================================
spring.application.name=colisender

# ===================================================================
# CONFIGURATION DE LA CONNEXION POSTGRESQL
# ===================================================================
# Assure-toi que la base de données nommée "colisender" existe bien dans ton PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/colisender
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURATION JPA / HIBERNATE
# ===================================================================
# "update" permet à Spring de créer automatiquement les tables 'utilisateur' 
# et 'verification_identite' au démarrage sans écraser tes données existantes.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Affiche et formate proprement les requêtes SQL dans la console de VS Code pour le débuggage
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURATION DE LA TAILLE DES FICHIERS (CNI & SELFIES)
# ===================================================================
# Augmente la limite pour accepter les photos haute résolution des smartphones (10 Mo max)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===================================================================
# CONFIGURATION DE L'ENVOI D'EMAILS (GMAIL SMTP SERVER)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=miguelnzoukouo@gmail.com

# /!\ METS ICI LES 16 LETTRES GENEREES PAR GOOGLE (SANS LES ESPACES)
# N'utilise pas ton mot de passe habituel, sinon Google bloquera la connexion.
spring.mail.password=nczh dgki asdp rktg

# Paramètres de sécurité obligatoires pour le protocole TLS de Google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true